Add packaging info to architecture templates
android/architecture-templates pull request #31
Opened 2022-11-01 06:26 UTC by tunjid

2022-11-02 08:58 UTC, mmoczkowski approved these changes

2022-11-02 09:44 UTC, JoseAlcerreca requested changes
This file needs to be removed in the customizer script, otherwise it adds noise to the template.
Also, CI should check that this file is removed after the script is run. I can do this (in a couple of days).

2022-11-15 12:02 UTC, merged

2022-11-24 14:17 UTC, JoseAlcerreca commented
This is currently broken because there is no project in `main`

2022-11-25 09:27 UTC, JoseAlcerreca commented
A fix has been proposed internally to point to the appropriate branches, so no action needed here.